name: Build Docker Image

on: 
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        uses: k15g/action-load-env@edge

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [edge]
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: klakegg/sass:edge
          platforms: linux/amd64,linux/arm64

      - name: Build and push [latest]
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          tags: klakegg/sass:${{ env.SASS_VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push [latest]
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          tags: klakegg/sass:latest
          platforms: linux/amd64,linux/arm64